force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADDRESSID-{0000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Karachi</fullName>
            </value>
            <value>
                <fullName>Lahore</fullName>
            </value>
            <value>
                <fullName>Colombo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>SriLanka</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Bharat</fullName>
            </value>
            <value>
                <fullName>China</fullName>
                <isActive>false</isActive>
                <label>China</label>
            </value>
            <value>
                <fullName>India</fullName>
                <isActive>false</isActive>
                <label>India</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujarath</fullName>
            </value>
            <value>
                <fullName>Sindh</fullName>
            </value>
            <value>
                <fullName>SriLanka State</fullName>
            </value>
            <value>
                <fullName>Japan State</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APPLICANTID-{00000000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Police_Verification__c.field-meta.xml
<CustomField>
    <fullName>Police_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Police Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchApplicantToAddress.cls
global class BatchApplicantToAddress implements Database.Batchable<sObject>{

	global Database.queryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator('Select Id, Police_Verification__c, Gender__c from Applicant__c where Police_Verification__c=true');
	}
	
	global void execute(Database.BatchableContext BC, List<Applicant__c> appList){
	
		Map<Id,Applicant__c> appMap = new Map<Id,Applicant__c>(appList);
		
		List<Address__c> adrList = new List<Address__c>();		
		for(Address__c objAdr : [Select Id, City__c, State__c, Country__c,Applicant__c from Address__c where  Applicant__c IN : appMap.keySet()]){
			adrList.add(objAdr);
		}
		
		if(!adrList.isEmpty()){
		
			for(Address__c objAdr : adrList){
				if(appMap.containsKey(objAdr.Applicant__c)){
					if(appMap.get(objAdr.Applicant__c).Gender__c == 'Male'){						
						objAdr.Country__c = 'Bharat';
						objAdr.State__c = 'Maharashtra';
						objAdr.City__c = 'Pune';
					}
					else{
							if(appMap.get(objAdr.Applicant__c).Gender__c == 'Female'){						
									objAdr.Country__c = 'Bharat';
									objAdr.State__c = 'Maharashtra';
									objAdr.City__c = 'Nagpur';
						}
							else{
									objAdr.City__c = null;
							
							}
					
					}
				}
			}
			
			Database.update(adrList, false);
		}
	
	}
	
	global void finish(Database.BatchableContext BC){
	
	}



}