force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APPLICANTID-{00000000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Police_Verification__c.field-meta.xml
<CustomField>
    <fullName>Police_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Police Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchApplicantPoliceVer.cls
global class BatchApplicantPoliceVer implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC){
           return Database.getQueryLocator('select Id, Police_Verification__c, Gender__c from Applicant__c where Gender__c=\'Male\' and Police_Verification__c=false');
    }
    
    global void execute(Database.BatchableContext BC, List<Applicant__c> applicantList){
        if(!applicantList.isEmpty()){
            for(Applicant__c objApp : applicantList){
                objApp.Police_Verification__c = true;
            }
            
            Database.update(applicantList,false);
        }
    }
    global void finish(Database.BatchableContext BC){
        
    }
}