force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APPLICANTID-{00000000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Pan_Card__c.field-meta.xml
<CustomField>
    <fullName>Pan_Card__c</fullName>
    <label>Pan Card</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Police_Verification__c.field-meta.xml
<CustomField>
    <fullName>Police_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Police Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchApplicantPoliceVerTest.cls
@isTest(seeAllData = false)
public class BatchApplicantPoliceVerTest {
    
    
    public static testMethod void testBatchMethod(){
        
        List<Applicant__c> appListInsert = new List<Applicant__c>(); 
        for(Integer i=1; i<=200; i++){
            Applicant__c objApp = new Applicant__c(First_Name__c='Bunty'+i , Last_Name__c='Modi'+i, Pan_Card__c='AVTPP9090R', Gender__c='Male');
            appListInsert.add(objApp);            
        }
        if(!appListInsert.isEmpty()){
            Database.Insert(appListInsert, false);
        }
        
        Test.startTest();
        	Database.executeBatch(new BatchApplicantPoliceVer(), 200); //Code Coverage
        Test.stopTest(); 
        
        //Tally Business Logic
        
        System.assertEquals(200 , [Select Id from Applicant__c where Police_Verification__c = true].size()); 
        
        
    }
}