force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APPLICANTID-{00000000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email Id</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchApplicantBirthdayEmail.cls
global class BatchApplicantBirthdayEmail implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator ('Select Id,Name,  First_Name__c, Last_Name__c, Email_Id__c, DOB__c from Applicant__c where Email_Id__c !=null and DOB__c !=null ');
    }
    
    global void execute(Database.BatchableContext BC, List<Applicant__c> appList){               
       
        List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        
        if(!appList.isEmpty()){
            for(Applicant__c objApp : appList){
                
                Integer birthDay =  objApp.DOB__c.day(); //26   26 March 1980
                Integer todayDay =   system.today().day(); //26  26 March 2024
               
                Integer birthMonth =     objApp.DOB__c.month(); //03  26 March 1980
				Integer todayMonth =   system.today().month(); //03  26 March 2024

                
                if(birthDay == todayDay && birthMonth== todayMonth){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(new String[] {objApp.Email_Id__c});
                    mail.setSenderDisplayName('Silver Micro');
                    mail.setSubject('Happy Birthday');
                    mail.setPlainTextBody('Hi '+objApp.First_Name__c+', \n Happy Birthday to you. \n Team \n Zingalala Pvt Ltd.');
                    mailList.add(mail);
                    
                    
                }
                
                
            }
            
            if(!mailList.isEmpty())
            		Messaging.sendEmail(mailList);
        } 
    }
    
    global void finish(Database.BatchableContext BC){
        
        
    }
    
}